# Access ResOpsUS historical reservoir operations dataset ([res_ops_us](https://hf-hydrodata.readthedocs.io/en/latest/gen_res_ops_us.html))

This notebook provides a walk-through of how to access the reservoir operations dataset, ResOpsUS, described in [Steyaert et. al 2022](https://www.nature.com/articles/s41597-022-01134-7).

Please see the full `res_ops_us` [dataset documentation page](https://hf-hydrodata.readthedocs.io/en/latest/gen_res_ops_us.html) for additional citation references for the details on how this dataset was produced.

In [1]:
# Import packages
import hf_hydrodata as hf

In [ ]:
# You need to register on https://hydrogen.princeton.edu/pin 
# and run the following with your registered information
# before you can use the hydrodata utilities
hf.register_api_pin("your_email", "your_pin")

## Example: Request reservoir inflow data for sites within a HUC2 region that have at least 1 observation within WY2003

In [2]:
options = {
    "dataset": "res_ops_us", 
    "variable": "reservoir_inflow",
    "temporal_resolution": "daily",
    "aggregation": "mean",
    "huc_id": ["1802"],
    "date_start": "2002-10-01",
    "date_end": "2003-09-30",
    "grid": "conus2",
    "min_num_obs": 1
}
 
inflow_data = hf.get_point_data(options)
inflow_data.head()

,date,ResOpsUS-132,ResOpsUS-133,ResOpsUS-144,ResOpsUS-148,ResOpsUS-168,ResOpsUS-173,ResOpsUS-182,ResOpsUS-185
0,2002-10-01,81.184,86.196,-1.161,74.020,17.925,NaN,15.093,-7.277
1,2002-10-02,85.998,86.366,-0.170,50.007,18.972,NaN,20.048,-9.968
2,2002-10-03,92.398,86.196,0.481,58.587,23.191,NaN,18.661,3.936
3,2002-10-04,102.478,87.357,-0.170,62.495,1312.427,NaN,23.616,-1.557
4,2002-10-05,91.718,30.809,-0.170,41.286,NaN,NaN,24.494,0.198

The above example also works for the variable `reservoir_outflow`.

## Example: Request reservoir evaporation data for a single reservoir ID for WY2003

In [3]:
options = {
    "dataset": "res_ops_us", 
    "variable": "reservoir_evaporation",
    "temporal_resolution": "daily",
    "aggregation": "sum",
    "site_ids": ["ResOpsUS-223"],
    "date_start": "2002-10-01",
    "date_end": "2003-09-30",
}

evaporation_data = hf.get_point_data(options)
evaporation_data.head()

         date  ResOpsUS-223
0  2002-10-01         48.26
1  2002-10-02         55.88
2  2002-10-03         53.34
3  2002-10-04         48.26
4  2002-10-05         48.26

The above example also works for the variable `reservoir_storage`.

## Example: Request reservoir water elevation data for a single reservoir ID for WY2003

In [4]:
options = {
    "dataset": "res_ops_us", 
    "variable": "reservoir_water_elevation",
    "temporal_resolution": "daily",
    "aggregation": "-",
    "huc_id": ["1802"],
    "date_start": "2002-10-01",
    "date_end": "2003-09-30",
    "grid": "conus2",
    "min_num_obs": 1
}
 
water_elevation_data = hf.get_point_data(options)
water_elevation_data.head()

         date  ResOpsUS-168  ResOpsUS-182  ResOpsUS-185
0  2002-10-01       160.127       127.236       128.882
1  2002-10-02       160.093       127.147       128.854
2  2002-10-03       160.197       127.056       128.845
3  2002-10-04       160.243       126.980       128.830
4  2002-10-05       160.258       126.903       128.818